leagues:
  - name: "French Ligue 1"
    slug: "french_ligue_1"
    sport_key: "france-ligue-1"
    odds_time_limit: 9 
  - name: "English Premier League"
    slug: "english_premier_league"
    sport_key: "england-premier-league"
    odds_time_limit: 9 
  - name: "Spanish La Liga"
    slug: "spanish_la_liga"
    sport_key: "spain-laliga"
    odds_time_limit: 9 
  - name: "German Bundesliga"
    slug: "german_bundesliga"
    sport_key: "germany-bundesliga"
    odds_time_limit: 9 
  - name: "Italian Serie A"
    slug: "italian_serie_a"
    sport_key: "italy-serie-a"
    odds_time_limit: 9
  - name: "UEFA Champions League"
    slug: "uefa_champions_league"
    sport_key: "international-clubs-uefa-champions-league"
    odds_time_limit: 9
  - name: "Portuguese Primeira Liga"
    slug: "portuguese_primeira_liga"
    sport_key: "portugal-liga-portugal"
    odds_time_limit: 7
  - name: "Belgian Pro League"
    slug: "belgian_pro_league"
    sport_key: "belgium-pro-league"
    odds_time_limit: 7
  - name: "English Sky Bet Championship"
    slug: "english_sky_bet_championship"
    sport_key: "england-championship"
    odds_time_limit: 7
  - name: "Turkish Super Cup"
    slug: "turkish_super_cup"
    sport_key: "turkiye-1-lig"
    odds_time_limit: 7
  - name: "Dutch Eerste Divisie"
    slug: "dutch_eerste_divisie"
    sport_key: "netherlands-eerste-divisie"
    odds_time_limit: 7
  # - name: "Romanian Liga I"
  #   slug: "romanian_liga_i"
  #   sport_key: "romania-superliga"
  #   odds_time_limit: 5 

  # - name: "UEFA Europa Conference League"
  #   slug: "uefa_europa_conference_league"
  #   sport_key: "international-clubs-uefa-conference-league"
  #   odds_time_limit: 7

    
